# Generated by Django 3.1.1 on 2020-09-14 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_Id', models.CharField(max_length=10, primary_key='True', serialize=False)),
                ('first_Name', models.CharField(max_length=10)),
                ('last_Name', models.CharField(max_length=10)),
                ('email', models.TextField(unique='true')),
                ('password', models.TextField()),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_Id', models.CharField(max_length=10, primary_key='True', serialize=False)),
                ('product_Name', models.CharField(max_length=20)),
                ('product_Price', models.FloatField()),
                ('product_Quantity', models.IntegerField()),
                ('upload_Id', models.CharField(max_length=11)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('customer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
